node index.js bsc_testnet distributeBNB 1 0.09
node index.js bsc_testnet distributeBNB 2 0.09
node index.js bsc_testnet distributeBNB 3 0.09
node index.js bsc_testnet distributeBNB 4 0.09
node index.js bsc_testnet distributeBNB 5 0.09
node index.js bsc_testnet distributeBNB 6 0.09
node index.js bsc_testnet distributeBNB 7 0.09
node index.js bsc_testnet distributeBNB 8 0.09
node index.js bsc_testnet distributeBNB 9 0.09
node index.js bsc_testnet distributeBNB 10 0.09
