node index.js bsc_mainnet distributeBNB 1 0.09
node index.js bsc_mainnet distributeBNB 2 0.09
node index.js bsc_mainnet distributeBNB 3 0.09
node index.js bsc_mainnet distributeBNB 4 0.09
node index.js bsc_mainnet distributeBNB 5 0.09
node index.js bsc_mainnet distributeBNB 6 0.09
node index.js bsc_mainnet distributeBNB 7 0.09
node index.js bsc_mainnet distributeBNB 8 0.09
node index.js bsc_mainnet distributeBNB 9 0.09
node index.js bsc_mainnet distributeBNB 10 0.09
